const VotingType = {
  VOTACION_GENERAL: "VOTACION_GENERAL",
  ARTICULO: "ARTICULO",
  APARTAMIENTO: "APARTAMIENTO",
  RATIFICACION: "RATIFICACION",
  DIA_NACIONAL: "DIA_NACIONAL",
  PATRIMONIO: "PATRIMONIO",
  REGIMEN: "REGIMEN"
};

export default VotingType;
